######################################################################
# Automatically generated by qmake (2.01a) Thu May 19 17:27:54 2011
######################################################################

TEMPLATE = app
TARGET = mytop
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += topwidget.h
SOURCES += main.cpp topwidget.cpp
